version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - 80:80

  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - 9115:9115

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090